spring:
  data:
    mongodb:
      host: localhost
      port: 28018
      database: tar-demo
      embedded: true
      preload: true
  mail:
    host: postfix.maredit.net
    port: 25
    username: no-reply@maredit.de
    password: lkvSdsE9YroldisNLVtdpVO4
spring.profiles.include: dummyLdapService
