##### Service test configuration #####
spring:
  profiles: serviceTest
  thymeleaf:
    cache: false  
  data:
    mongodb:
      host: localhost
      port: 28018
      database: tar-serviceTest
      embedded: true
      preload: true
  mail:
    host: localhost
    port: 1600
    username:
    password:
    additionalRecipients:
      - mareditTarTest@dontsendmespam.de
  ldap:
    host: localhost
    port: 1600
    userLookUpDN: ou=users,o=maredit,dc=de
    applicationUserDN: cn=tar-users,cn=tar,ou=services,o=maredit,dc=de
    applicationSupervisorDN: cn=tar-supervisors,cn=tar,ou=services,o=maredit,dc=de
    readUser: cn=read,cn=ldap,ou=services,o=maredit,dc=de
    readPassword: read
    groupLookUpDN: ou=services,o=maredit,dc=de
    groupLookUpAttribute: member
    userBindDN: uid=$username,ou=users,o=maredit,dc=de
    disableSSL: true
spring.profiles.include: dummyCalendarService,smtpMailService
