spring:
  profiles:
    active: dev 
---
##### Development configuration #####
spring:
  profiles: dev
  thymeleaf:
    cache: false
  data:
    mongodb:
      host: localhost
      port: 28018
      database: tar
      embedded: true
      preload: true
---
##### Test configuration #####
spring:
  profiles: test
  thymeleaf:
    cache: false  
  data:
    mongodb:
      host: localhost
      port: 28018
      database: tar
      embedded: false
      preload: true
---
##### Production configuration #####
spring:
  profiles: prod
  data:
    mongodb:
      host: localhost
      port: 27017
      database: tar
      embedded: false 
      preload: false     