spring:
  profiles:
    active: localDev
---
##### 
spring:
  profiles: dummyServices
spring.profiles.include: dummyLdapService,dummyMailService
---
##### Development configuration #####
spring:
  profiles: localDev
  thymeleaf:
    cache: false
  data:
    mongodb:
      host: localhost
      port: 28018
      embedded: true
      preload: true
      database: tar-dev
  mail:
    additionalRecipients:
      - mareditTarTest@dontsendmespam.de
    urlToVacation: http://localhost:8080
  number:
    build: "0001"
spring.profiles.include: dummyServices
---
##### Test configuration #####
spring:
  profiles: test
  thymeleaf:
    cache: false  
  data:
    mongodb:
      host: localhost
      port: 28018
      embedded: true
      preload: true
      database: tar-test
  mail:
    additionalRecipients:
      - mareditTarTest@dontsendmespam.de
spring.profiles.include: dummyServices
