spring:
  profiles: dev
  data:
    mongodb:
      host: localhost
      port: 28018
      database: tar
---
spring:
  profiles: test
  data:
    mongodb:
      host: localhost
      port: 28018
      database: tar
---
spring:
  profiles: prod
  data:
    mongodb:
      host: localhost
      port: 27017
      database: tar