spring:
  profiles:
    active: dev 
---
##### Development configuration #####
spring:
  profiles: dev
  thymeleaf:
    cache: false
  data:
    mongodb:
      host: localhost
      port: 28018
      database: tar
      embedded: true
      preload: true
---
##### Test configuration #####
spring:
  profiles: test
  thymeleaf:
    cache: false  
  data:
    mongodb:
      host: localhost
      port: 28018
      database: tar
      embedded: true
      preload: true
---
##### LDAP Test configuration #####
spring:
  profiles: ldapTest
  ldap:
    host: localhost
    port: 1600
    userLookUpDN: ou=users,o=maredit,dc=de
    applicationUserDN: cn=tar-users,cn=tar,ou=services,o=maredit,dc=de
    readUser: cn=read,cn=ldap,ou=services,o=maredit,dc=de
    readPassword: read
    groupLookUpDN: ou=services,o=maredit,dc=de
    groupLookUpAttribute: member
    userBindDN: uid=$username,ou=users,o=maredit,dc=de
    disableSSL: true
---
##### Production configuration #####
spring:
  profiles: prod
  data:
    mongodb:
      host: tar-db.maredit.net
      port: 27017
      database: tar
      embedded: false
      preload: false 
  ldap:
    host: ldap-master.maredit.net
    port: 636
    userLookUpDN: ou=users,o=maredit,dc=de
    applicationUserDN: cn=tar-users,cn=tar,ou=services,o=maredit,dc=de
    readUser: cn=read,cn=ldap,ou=services,o=maredit,dc=de
    readPassword: 7Ey8vHzPPZrdWA
    groupLookUpDN: ou=services,o=maredit,dc=de
    groupLookUpAttribute: member
    userBindDN: uid=$username,ou=users,o=maredit,dc=de
    
