spring:
  profiles:
    active: dev
---
##### 
spring:
  profiles: dummyServices
spring.profiles.include: dummyLdapService, dummyMailService
---
##### Development configuration #####
spring:
  profiles: dev
  thymeleaf:
    cache: false
  data:
    mongodb:
      host: localhost
      port: 28018
      embedded: true
      preload: true
      database: tar-dev
spring.profiles.include: dummyServices
---
##### Test configuration #####
spring:
  profiles: test
  thymeleaf:
    cache: false  
  data:
    mongodb:
      host: localhost
      port: 28018
      embedded: true
      preload: true
      database: tar-test
spring.profiles.include: dummyServices
