spring:
  profiles:
    active: dev
---
##### Development configuration #####
spring:
  profiles: dev
  thymeleaf:
    cache: false
  data:
    mongodb:
      host: localhost
      port: 28018
      database: tar
      embedded: true
      preload: true
  ldap:
    host: ldap-master.maredit.net
    port: 636
    userLookUpDN: ou=users,o=maredit,dc=de
    userBindDN: uid=$username,ou=users,o=maredit,dc=de
    applicationUserDN: cn=tar-users,cn=tar,ou=services,o=maredit,dc=de
    applicationTeamleaderDN: cn=teamleiter,cn=teams,ou=groups,o=maredit,dc=de
    groupLookUpDN: ou=services,o=maredit,dc=de
    groupLookUpAttribute: member
    readUser: cn=read,cn=ldap,ou=services,o=maredit,dc=de
    readPassword: 7Ey8vHzPPZrdWA
---
##### Test configuration #####
spring:
  profiles: test
  thymeleaf:
    cache: false  
  data:
    mongodb:
      host: localhost
      port: 28018
      database: tar
      embedded: true
      preload: true
---
##### Service test configuration #####
spring:
  profiles: serviceTest
  thymeleaf:
    cache: false  
  data:
    mongodb:
      host: localhost
      port: 28018
      database: tar
      embedded: true
      preload: true
  mail:
    host: localhost
    port: 1600
    username:
    password:
  ldap:
    host: localhost
    port: 1600
    userLookUpDN: ou=users,o=maredit,dc=de
    applicationUserDN: cn=tar-users,cn=tar,ou=services,o=maredit,dc=de
    applicationTeamleaderDN: cn=teamleiter,cn=teams,ou=groups,o=maredit,dc=de
    readUser: cn=read,cn=ldap,ou=services,o=maredit,dc=de
    readPassword: read
    groupLookUpDN: ou=services,o=maredit,dc=de
    groupLookUpAttribute: member
    userBindDN: uid=$username,ou=users,o=maredit,dc=de
    disableSSL: true
---
##### Production configuration #####
spring:
  profiles: prod
  data:
    mongodb:
      host: tar-db.maredit.net
      port: 27017
      database: tar
      embedded: false
      preload: false 
  ldap:
    host: ldap-master.maredit.net
    port: 636
    userLookUpDN: ou=users,o=maredit,dc=de
    applicationUserDN: cn=tar-users,cn=tar,ou=services,o=maredit,dc=de
    applicationTeamleaderDN: cn=teamleiter,cn=teams,ou=groups,o=maredit,dc=de
    readUser: cn=read,cn=ldap,ou=services,o=maredit,dc=de
    readPassword: 7Ey8vHzPPZrdWA
    groupLookUpDN: ou=services,o=maredit,dc=de
    groupLookUpAttribute: member
    userBindDN: uid=$username,ou=users,o=maredit,dc=de
  mail:
    host: postfix.maredit.net
    port: 25
    username: no-reply@maredit.de
    password: lkvSdsE9YroldisNLVtdpVO4
