spring:
  data:
    mongodb:
      host: localhost
      port: 28018
      database: tar-demo
      embedded: true
      preload: false
  mail:
    additionalRecipients:
      - mareditTarTest@dontsendmespam.de
  exchange:
    service: https://mac.hex2013.com/EWS/Exchange.asmx
    user: no-reply@maredit.de
    password: lkvSdsE9YroldisNLVtdpVO4
spring.profiles.include: dummyLdapService,exchangeMailService,dummyCalendarService
