spring:
  profiles:
    active: dev 
---
##### Development configuration #####
spring:
  profiles: dev
  thymeleaf:
    cache: false
  data:
    mongodb:
      host: localhost
      port: 28018
      database: tar
      embedded: true
  mail:
    host: localhost
    port: 2025
    username: tar
    password:
    properties:
      environment: dev
---
##### Test configuration #####
spring:
  profiles: test
  thymeleaf:
    cache: false  
  data:
    mongodb:
      host: localhost
      port: 28018
      database: tar
      embedded: false
---
##### Production configuration #####
spring:
  profiles: prod
  data:
    mongodb:
      host: localhost
      port: 27017
      database: tar
      embedded: false      