spring:
  data:
    mongodb:
      host: localhost
      port: 28018
      database: tar-demo
      embedded: true
      preload: false
  mail:
    host: postfix.maredit.net
    port: 25
    username: no-reply@maredit.de
    password: lkvSdsE9YroldisNLVtdpVO4
    additionalRecipients:
      - mareditTarTest@dontsendmespam.de
    urlToVacation: https://dev.tar.maredit.net
spring.profiles.include: dummyLdapService
