spring:
  profiles:
    active: dev 
---
##### Development configuration #####
spring:
  profiles: dev
  thymeleaf:
    cache: false
  data:
    mongodb:
      host: localhost
      port: 28018
      database: tar
      embedded: true
      preload: true
  ldap:
    host: ldap-master.maredit.net
    port: 636
    userLookUpDN: ou=users,o=maredit,dc=de
    apllicationUserDN: cn=tar-users,cn=tar,ou=services,o=maredit,dc=de
    readUser: cn=read,cn=ldap,ou=services,o=maredit,dc=de
    readPassword: 7Ey8vHzPPZrdWA  
  mail:
    host: localhost
    port: 2025
    username: tar
    password:
    properties:
      environment: dev
---
##### Test configuration #####
spring:
  profiles: test
  thymeleaf:
    cache: false  
  data:
    mongodb:
      host: localhost
      port: 28018
      database: tar
      embedded: true
      preload: true
  mail:
    host: localhost
    port: 2025
    username: tar
    password:
    properties:
      environment: dev
  ldap:
    host: ldap-master.maredit.net
    port: 636
    userLookUpDN: ou=users,o=maredit,dc=de
    apllicationUserDN: cn=tar-users,cn=tar,ou=services,o=maredit,dc=de
    readUser: cn=read,cn=ldap,ou=services,o=maredit,dc=de
    readPassword: 7Ey8vHzPPZrdWA
---
##### Production configuration #####
spring:
  profiles: prod
  data:
    mongodb:
      host: tar-db.maredit.net
      port: 27017
      database: tar
      embedded: false 
      preload: false 
  ldap:
    host: ldap-master.maredit.net
    port: 636
    userLookUpDN: ou=users,o=maredit,dc=de
    apllicationUserDN: cn=tar-users,cn=tar,ou=services,o=maredit,dc=de
    readUser: cn=read,cn=ldap,ou=services,o=maredit,dc=de
    readPassword: 7Ey8vHzPPZrdWA          
