spring:
  profiles:
    active: dev
---
##### 
spring:
  profiles: dummyServices
spring.profiles.include: dummyLdapService,dummyMailService,dummyCalendarService
---
##### Development configuration #####
spring:
  profiles: dev
  thymeleaf:
    cache: false
  data:
    mongodb:
      host: localhost
      port: 28018
      embedded: true
      preload: true
      database: tar-dev
  mail:
    additionalRecipients:
      - mareditTarTest@dontsendmespam.de
  exchange:
    service: https://mac.hex2013.com/EWS/Exchange.asmx
###    user: 
###    password:
###    calendar: 
  number:
    build: "0001"
spring.profiles.include: dummyServices
---
##### Test configuration #####
spring:
  profiles: test
  thymeleaf:
    cache: false  
  data:
    mongodb:
      host: localhost
      port: 28018
      embedded: true
      preload: true
      database: tar-test
  mail:
    additionalRecipients:
      - mareditTarTest@dontsendmespam.de
spring.profiles.include: dummyServices
