spring:
  profiles:
    active: dev 
---
##### Development configuration #####
spring:
  profiles: dev
  thymeleaf:
    cache: false
  data:
    mongodb:
      host: localhost
      port: 28018
      database: tar
      embedded: true
  ldap:
    host: ldap-master.maredit.net
    port: 636
    userLookUpDN: ou=users,o=maredit,dc=de
    applicationUserDN: cn=tar-users,cn=tar,ou=services,o=maredit,dc=de
    readUser: cn=read,cn=ldap,ou=services,o=maredit,dc=de
    readPassword: 7Ey8vHzPPZrdWA
    groupLookUpDN: ou=groups,o=maredit,dc=de
    groupLookUpAttribute: memberUid
    userBindDN: uid=$username,ou=users,o=maredit,dc=de
---
##### Test configuration #####
spring:
  profiles: test
  thymeleaf:
    cache: false  
  data:
    mongodb:
      host: localhost
      port: 28018
      database: tar
      embedded: false
  ldap:
    host: ldap-master.maredit.net
    port: 636
    userLookUpDN: ou=users,o=maredit,dc=de
    apllicationUserDN: cn=tar-users,cn=tar,ou=services,o=maredit,dc=de
    readUser: cn=read,cn=ldap,ou=services,o=maredit,dc=de
    readPassword: 7Ey8vHzPPZrdWA
---
##### Production configuration #####
spring:
  profiles: prod
  data:
    mongodb:
      host: localhost
      port: 27017
      database: tar
      embedded: false
